def lowerChar(char):  #define the function which converts upper case...
    if char >= 'A' and char <= 'Z': # ...using string comparison...
        char = chr(ord(char) + 32) #...and the ASCII table
    return char